## Introduction NumPy

In [1]:
!pip install numpy

In [2]:
## NumPy : match calculations

In [3]:
type([1,2,3,4,5])

list

In [4]:
import numpy as np

In [5]:
len(dir(np))

608

In [6]:
## Numpy array from List

arr = np.array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [7]:
## Numpy array from tuple

arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
## Numpy array from set

arr = np.array({1,2,3,4,5,6,6,88})
print(arr)
print(type(arr))

{1, 2, 3, 4, 5, 6, 88}
<class 'numpy.ndarray'>


In [9]:
# Numpy array : Attributes

arr = np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)#dimension of the array
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

[1 2 3 4 5]
1
(5,)
5
int32
4


In [10]:
arr = np.array([[1,2,3,4,5],[10,20,30,40,50],[100,200,300,400,500]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

[[  1   2   3   4   5]
 [ 10  20  30  40  50]
 [100 200 300 400 500]]
2
(3, 5)
15
int32
4


In [11]:
arr = np.array([[[1,2,3,4,5],[10,20,30,40,50],[100,200,300,400,500],[1000,2000,3000,4000,5000]]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

[[[   1    2    3    4    5]
  [  10   20   30   40   50]
  [ 100  200  300  400  500]
  [1000 2000 3000 4000 5000]]]
3
(1, 4, 5)
20
int32
4


In [12]:
## Ones() and Zeros()

arr = np.ones((5,5))
print(arr)

arr = np.zeros((5,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
## copy

import numpy as np
a = np.array([1,2,3])
print(id(a))

b = a
print(id(b))

c = a.copy()
print(id(c))

a[0] = 858585

print(a)
print(b)
print(c)

2282355682832
2282355682832
2282355680816
[858585      2      3]
[858585      2      3]
[1 2 3]


In [14]:
# arange
import numpy as np
arr = np.arange(0,20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [15]:
import numpy as np
arr = np.arange(0,222,22)
print(arr)

[  0  22  44  66  88 110 132 154 176 198 220]


In [16]:
## Linspace

import numpy as np
arr = np.linspace(0,100,5)
print(arr)

[  0.  25.  50.  75. 100.]


In [17]:
## Arthmetic operation

a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40,50])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
[1 2 3 4 5]


In [18]:
## Matrix product

import numpy as np
a = np.arange(0.,9).reshape(3,3)
b = np.ones((3,3))

print(a)
print(b)

print(np.dot(a,b))

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]


In [19]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
## Universal functions

import numpy as np
arr = np.array([4,9,16,25])

print(arr)
print(np.sqrt(arr))
print(np.log(arr))

[ 4  9 16 25]
[2. 3. 4. 5.]
[1.38629436 2.19722458 2.77258872 3.21887582]


In [21]:
print(arr.sum())
print(arr.min())
print(arr.max())
print(arr.mean())
print(arr.std())

54
4
25
13.5
7.88986691902975


In [22]:
## Logical functions
arr = np.array([[True , False ],[True , True]])
print(arr)

#print(np.all([arr], axis = 0))
print(np.all([arr], axis = 1))

[[ True False]
 [ True  True]]
[[ True False]]


In [23]:
arr = np.array([[True , False ],[True , True]])
print(arr)

print(np.any([arr]))
print(np.any([arr], axis = 1))

[[ True False]
 [ True  True]]
True
[[ True  True]]
