In [1]:
## Indexing in Numpy array

In [2]:
import numpy as np
arr = np.arange(21,26)

arr

array([21, 22, 23, 24, 25])

In [3]:
## Get 22
print(arr[1])
print(arr[2])
print(arr[3])

22
23
24


In [4]:
print(arr[1:4])
print(arr[-4:-1])


[22 23 24]
[22 23 24]


In [5]:
## Indexind 2D

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
a[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [7]:
a[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [8]:
a[-2:-1,-2:1]

array([], shape=(1, 0), dtype=int32)

In [9]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
print(a.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(a)

[1 2 3 4 5 6 7 8 9]


In [12]:
print(a.resize(3,3))
print(a)

None
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
## ravel 
a = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(a)
print(a.ndim)
print(a.ravel())
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
## transpose
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
np.transpose(a)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [18]:
## Joining the arrays
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]]


In [19]:
## Axis = None
np.concatenate((a,b), axis = None)

array([1, 2, 3, 4, 5, 6])

In [20]:
## Axis + None
np.concatenate((a,b.T),axis = 1)


array([[1, 2, 5],
       [3, 4, 6]])

In [21]:
## Axis = 0
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
### Stacking

import numpy as np
a = np.array([1,2,3])
b = np.array([10, 20, 30])

np.stack((a,b))

array([[ 1,  2,  3],
       [10, 20, 30]])

In [23]:
import numpy as np
a = np.array([1,2,3])
b = np.array([10,20,30])
c = np.array([100,200,300])

np.stack((a,b,c))

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [24]:
## Splt arrays : split(), hslit(), vsplit()


In [25]:
x = np.arange(9)
print(x)
np.split(x,3)

[0 1 2 3 4 5 6 7 8]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [26]:
a = np.arange(16).reshape((4,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [28]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [29]:
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]